FROM node:16-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci --only=production

COPY src ./src
COPY migrations ./migrations

ENV NODE_ENV=production

CMD ["node", "-r", "dotenv/config", "src/workers/index.js"]
